## Kanagawa color scheme
gui:
  theme:
    activeBorderColor:
      - '#957FB8'
      - bold
    inactiveBorderColor:
      - '#54546D'
    selectedLineBgColor:
      - '#2D4F67'
    defaultFgColor:
      - '#DCD7BA'
    unstagedChangesColor:
      - '#C34043'
