#Enable colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides "xterm-256color:RGB"

# Enable mouse support
set -g mouse on

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config Reloaded."

#Scrollback
set -g history-limit 50000

# Don't exit copy mode after yanking
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status line position
set-option -g status-position top

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#Vim motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tpm-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

#Auto save / Restore
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

# KANAGAWA TMUX THEME
set -g @plugin 'Nybkox/tmux-kanagawa'

# theme variants: wave (default), dragon, lotus
set -g @ukiyo-theme "kanagawa/dragon"

set -g @ukiyo-continuum-mode countdown

# keep terminal colors (important for nvim consistency)
set -g @kanagawa-ignore-window-colors true

# LOAD TPM 
run '~/.tmux/plugins/tpm/tpm'
