#Enable colors
set -g default-terminal "tmux-256color"
# set -ag terminal-overrides "xterm-256color:RGB"
set -ga terminal-overrides ",tmux-256color:RGB"
set-option -g focus-events on

# Reduce escape time for better vim experience
set -sg escape-time 0

#Chnage prefix to ctrl + space same as nvim
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Enable mouse support
set -g mouse on

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config Reloaded."

#Vim-style splits
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Vim-style splits
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#Scrollback
set -g history-limit 50000

# Don't exit copy mode after yanking
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status line position
set-option -g status-position top

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#Make new window after current index
bind c new-window -a -c "#{pane_current_path}" 
bind C new-window -c "#{pane_current_path}" 

#Rename windows to dir instead of process
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

#Vim motions
# set-window-option -g mode-keys vi
# bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi 'y' send -X copy-selection

# Vim-style copy mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection
set -g allow-passthrough on
set -s set-clipboard on
setw -g mode-style 'fg=#1F1F28,bg=#7E9CD8'

#Windows-swapping
bind -r Left swap-window -t -1 \; select-window -t -1
bind -r Right swap-window -t +1 \; select-window -t +1

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tpm-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

#Auto save / Restore
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# KANAGAWA TMUX THEME
# set -g @plugin 'Nybkox/tmux-kanagawa'

# theme variants: wave (default), dragon, lotus
set -g @ukiyo-theme "wave"

set -g @ukiyo-continuum-mode countdown

# keep terminal colors (important for nvim consistency)
set -g @ukiyo-ignore-window-colors true

# LOAD TPM
run '~/.tmux/plugins/tpm/tpm'
